version: "3.9"

services:
  backend:
    build: .
    container_name: ai_dashboard_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
             uvicorn dashboardbackend.asgi:application --host 0.0.0.0 --port 8000"

  db:
    image: postgres:14
    container_name: ai_dashboard_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: ai_dashboard_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
